import { serve } from "https://deno.land/std@0.192.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

/**
 * Schedules a review-request email 5 days after a consultation booking.
 * Called by handle-calendly-booking immediately after a booking is confirmed.
 *
 * Creates:
 *  - A row in review_requests (with a unique secure token)
 *  - A row in email_sequences (sequence_type = 'review_request', scheduled 5 days out)
 */
serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "*",
      },
    });
  }

  try {
    const { inquiryId, recipientEmail, recipientName, service } = await req.json();

    const SUPABASE_URL = (globalThis as any)?.Deno?.env?.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = (globalThis as any)?.Deno?.env?.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Supabase credentials not configured");
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Schedule 5 days (120 hours) from now
    const scheduledAt = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString();

    // 1. Insert the email_sequences row first (to get its id)
    const { data: seqRow, error: seqErr } = await supabase
      .from("email_sequences")
      .insert({
        inquiry_id: inquiryId,
        sequence_type: "review_request",
        step_number: 1,
        scheduled_at: scheduledAt,
        send_status: "pending",
      })
      .select("id")
      .single();

    if (seqErr) throw new Error(`email_sequences insert: ${seqErr.message}`);

    // 2. Create the review_request row (token auto-generated by DB default)
    const { data: reviewRow, error: reviewErr } = await supabase
      .from("review_requests")
      .insert({
        inquiry_id: inquiryId,
        sequence_id: seqRow.id,
        client_name: recipientName,
        client_email: recipientEmail,
        service: service ?? null,
      })
      .select("id, token")
      .single();

    if (reviewErr) throw new Error(`review_requests insert: ${reviewErr.message}`);

    return new Response(
      JSON.stringify({
        success: true,
        sequenceId: seqRow.id,
        reviewRequestId: reviewRow.id,
        scheduledAt,
      }),
      {
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
      },
    });
  }
});
